name: compilation test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install software
      run: sudo apt-get update; sudo apt-get install gfortran libopenmpi-dev libfftw3-dev
    - name: test compilation
      run: |
        cd src/
        make && make run && make clean
        make OMP+=-fopenmp OTH+=-D_IMPDIFF && make run && make clean
